### ISSUE TITLE
[Auth] Implement user verification feature

### ISSUE THREAD

**Issue by ahmedeid6842** [ahmedeid6842/How#50]
## Description: :speech_balloon: 
After the user register and provide his data like (username, email, password) a verification code that is valid for one hour will be sent to his email. 

After the code is sent, the user will try to verify his code and if it's right the account will mark as verified, Also consider to update Auth guard so the user who isn't verified will be consider as unAuth. 

## To-Do: :white_check_mark: 
- [x] Update the `User` entity to include `verificationCode`, `verificationCodeExpiration` and `isVerified`. 
- [x] Update the register method in the auth.service.ts file to add the generated `verificationCode` and `verificationCodeExpiration` set the `isVerified` to false when registering a user. 
  - Implement a private method `getVerificationCodeExpiration` to generate the code exiprate date.
  - Implement a private method `generateVerificationCode` to generate a verify code. 
  - update add user method to accept `verificationCode` and `verificationExpriresAt`
  - use `sendVerificationEmail` to send a verification code to user email.
- [x] Implement `sendVerificationEmail` method that accept `email`, `code` as parameter. and send the code to the passed email.
- [x] Implement the Verification controller `POST => auth/verify`
  - Implement A `VerifyDTO` that accept `email` and `code`.
  - Call `verifyEmail` service method to verify the passed code.
- [x] Implement `verifyEmail` service method to verify the passed code. 
  - Call `find` user to check if the provide email exists.
  - Math the provide code with the stored on.
  - Check `verificationCodeExpiration` to see if the code is still or not.
  - If everything is okay change `isVerified` property to true.
- [x] Update `AuthGuard` to check also if the user is verified or not. 

-----

<div align="center">
<img src="https://media.giphy.com/media/SyP24XyDVsavNPECoR/giphy.gif"/>
</div>
